### ISSUE TITLE
If constant value is left blank, the substitution of the value does not take place.

### ISSUE THREAD

**Issue by travism** [pajtai/grunt-php-set-constant#9]
Example: 
When trying to swap out value for DB_USER I noticed a problem if the constant is left empty. This code works:

File value

```
define('DB_USER', 'temp_user');
```

Grunt config

```
setPHPConstant : {

                DB_USER : {
                    constant : 'DB_USER',
                    value    : 'real_value',
                    file     : {path to file}
                }
```

---

Changing the define from:

```
define('DB_USER', 'temp_user');
```

to:

```
define('DB_USER', '');
```

Will result in the task not adding the 'real_value' of the constant.

**Comment by pajtai** [comment]
When you run, `grunt test` do they pass?

We have a [test for this case](https://github.com/pajtai/grunt-php-set-constant/blob/master/test/input/sample.php#L5), and it passes for me.

**Comment by pajtai** [comment]
@travism - does `grunt test` pass or fail? could you provide the php file and Gruntfile that is failing?
Thanks,
Peter.

**Comment by pajtai** [comment]
@travism - any updates about the tests or files in question?

**Comment by pajtai** [comment]
Closing because I cannot repro. 

If this can still be reprod in latest version, please include the problem files or output from the tests and I'll reopen and try to fix.
